### ISSUE TITLE
IFD News - footer text

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#1]
No pude agregar el Footer desde la edición. Si desde agregar.
![image](https://user-images.githubusercontent.com/34341691/39144693-ecca3b34-4707-11e8-835e-98289df6e3d8.png)
![image](https://user-images.githubusercontent.com/34341691/39144684-e1f55afe-4707-11e8-951c-31be55162137.png)

**Comment by angeledugo** [comment]
Validar nuevamente se realizo prueba y el footer text carga correctamente

**Comment by carlos-segovia** [comment]
Desde editar no funciona. 
Y si hay una IFD News que ya tiene cargado el texto del footer cuando se edita no aparece el texto en el form.
Fijate en esta que tiene texto de footer y cuando la quieres editar aparece vacio el campo:
http://ifd.sietepuentes.com/generar.php?id=122&tipo=ifdnew&oper=HTML&template=2

**Comment by angeledugo** [comment]
Se actualizo correctamente asi como la redireccion verificar nuevamente

**Comment by carlos-segovia** [comment]
Ahora si funciona.
