### ISSUE TITLE
IFD News - Edición no cambia la imagen

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#10]
Cuando edito un IFD News y quiero cambiar una imagen la selecciona pero al guardar los cambios no cambia la imagen.

**Comment by angeledugo** [comment]
Solucionado por favor verificar

**Comment by carlos-segovia** [comment]
Sigue sin funcionar.

**Comment by angeledugo** [comment]
Listo validado el cargue de imagenes en el proceso de edicion por favor validar

**Comment by carlos-segovia** [comment]
Lo mismo que el #2 funciona pero al confirmar la edición queda en el form y no redirecciona al listado de IFD News.

**Comment by angeledugo** [comment]
Listo solventado la redireccion

**Comment by robert-dm** [comment]
Redirección ok.
