### ISSUE TITLE
IFD News - Al importar en outlook se visualiza con errores de diseño el html

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#12]
El template generado se debe importar en outlook y debe visualizarse tal cual se visualiza en el html generado.  Pero se ve con varios errores en outlook.  Cabe destacar que la maqueta html fue probada en outlook y se veía perfecta.  
Estoy hablando de este IFD news que en la web se ve mejor que en el email importado http://ifd.sietepuentes.com/generar.php?id=131&tipo=ifdnew&oper=HTML&template=2 

Pasos a seguir:
1-Generar el html (se descarga localmente en la PC) http://ifd.sietepuentes.com/generar.php?id=131&tipo=ifdnew&oper=DOWN&template=2 
2-Abrir outlook (estoy usando outlook 2010)
3-Crear un nuevo email
4-Insertar un adjunto
5-Elegir el html descargado localmente, y utilizar la opción "Insertar como texto" de outlook.
![image](https://user-images.githubusercontent.com/35821871/39222669-463322c8-4814-11e8-84fc-94bb8f4184b5.png)

Los errores a destacar son:
a) El primer hyperlink "read more" debe estar alineado a la derecha
b) debe haber un espacio entre la imagen y el texto
c) debajo de la imagen entre la imagen y el texto debe haber espacio
d) El texto está mal alineado con diferente justificacion
e) debe haber un espacio entre el texto y el segundo botón "See full database"
f) Verificar la fuente, parece tener un tamaño mayor en outlook

![image](https://user-images.githubusercontent.com/35821871/39222686-61cce096-4814-11e8-972e-b8ee8a13ef6c.png)
![image](https://user-images.githubusercontent.com/35821871/39222706-85a9cfec-4814-11e8-82c4-b64cc222545b.png)
![image](https://user-images.githubusercontent.com/35821871/39222732-a4cab1f2-4814-11e8-8fb8-3ccfd7d293db.png)

**Comment by angeledugo** [comment]
Buenas tardes se realizaron varias pruebas con outlook llegando a la conclusion que tienes mas que ver con las version del mismo. es por ello que realizaron ajustes con la intencion de solventar los detalles mencionados por favor verificar.

**Comment by robert-dm** [comment]
Verifico que se ve mejor, sin embargo marco donde hay issues aún (estoy usando outlook 2010).  En que versión de outlook se ve idéntico al html?

El hyperlink read more, debería estar a la derecha
Debería haber un espacio entre el hyperlink read more y la línea separadora
Debería haber un espacio entre el subtítulo azul y la imagen

![image](https://user-images.githubusercontent.com/35821871/39274933-f111c0c8-48b9-11e8-86ce-165b62f08449.png)

**Comment by angeledugo** [comment]
por favor validar nuevamente los ajustes realizados

**Comment by robert-dm** [comment]
Así llega el email usando Outlook 2010, sigue habiendo pequeñas correcciones para hacer.

![image](https://user-images.githubusercontent.com/35821871/39277135-acd1d2b4-48c2-11e8-9331-b32f2196590b.png)

**Comment by angeledugo** [comment]
se actualizo el template validar por favor

**Comment by angeledugo** [comment]
Validar nueva actualizacion por favor.

**Comment by robert-dm** [comment]
Angel como hablamos por favor envianos un email desde el outlook 2016 y si se ve bien cerramos este issue y pagamos el milestone.

**Comment by angeledugo** [comment]
Se envio correo para validacion

**Comment by robert-dm** [comment]
El último correo se ve bien los botones solo faltaría lo que marco:

![image](https://user-images.githubusercontent.com/35821871/39338442-1c9e3e80-4999-11e8-94e4-3758a2d6f9e8.png)

**Comment by robert-dm** [comment]
Para evitar ver esa línea en mobile, por favor Angel prueba agregando esto, que nos comenta el maquetador:

<style type="text/css">
   p{
   -webkit-margin-before: 0em;
    -webkit-margin-after: 0em;
    }
