### ISSUE TITLE
Publicaciones - Link Open in browser

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#13]
El link Open in browser esta solo texto. Hay que agregarle el link para que abra en el navegador
![image](https://user-images.githubusercontent.com/34341691/39380060-a2cca9b6-4a33-11e8-8c4b-fee9e3c590fe.png)

**Comment by angeledugo** [comment]
Link actualizado

**Comment by carlos-segovia** [comment]
Listo!
