### ISSUE TITLE
Publicaciones - Links del Footer

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#14]
Los links del Footer en el mail se ven distintos que los de la maqueta:

Maqueta:
![image](https://user-images.githubusercontent.com/34341691/39380121-da13dd7c-4a33-11e8-9d3d-c1139bdd576b.png)

Mail:
![image](https://user-images.githubusercontent.com/34341691/39380139-ea3d24a6-4a33-11e8-952f-e59e349ebf6a.png)

**Comment by angeledugo** [comment]
vista actualizada

**Comment by carlos-segovia** [comment]
Esta mejor pero se sigue viendo distinto: 
- El tamaño de la tipografia es distinto.
- El subrayado es de distinto color.

Maqueta:
![image](https://user-images.githubusercontent.com/34341691/39407669-d8e368c4-4b9f-11e8-96f2-528d36e2bfae.png)

Mail:
![image](https://user-images.githubusercontent.com/34341691/39407665-c8295098-4b9f-11e8-97a6-e419bfa92eb2.png)

**Comment by angeledugo** [comment]
buen dia actualice el color del subrayado por favor validar en el envio gracias.

**Comment by carlos-segovia** [comment]
Listo!
