### ISSUE TITLE
Eventos - Issues para corregir

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#16]
Creé uno en eventos: http://ifd.sietepuentes.com/generar.php?id=70&tipo=news&oper=HTML&template=2

1-la imagen no se visualiza
![image](https://user-images.githubusercontent.com/35821871/39646240-21f84c72-4fb1-11e8-8796-e7ba8f80c734.png)

2-El texto de footer no tiene input en el formulario:
![image](https://user-images.githubusercontent.com/35821871/39646251-2f901838-4fb1-11e8-97fe-7386e78c0d1d.png)

3-Cambiar el orden a desc en los registros que se ven acá http://ifd.sietepuentes.com/newsletters.php y mostrar en la pantalla al menos 10 registros.

**Comment by angeledugo** [comment]
1. Se actualizo la ruta 
2. Los cambios de formularios seran acordados al final de las actividades establecidas
3.  Order actualizado

**Comment by robert-dm** [comment]
1.La imagen se muestra en dimensiones erróneas, la imagen debe ser croppeada en 547x309 o misma relación (como está en la maquetación)
2.No, en este caso el footer y su texto es parte de la actualización del template, el footer es requerido en forma dinámica para este template.
3.OK
4.En el altaNewsletter.php cambiar este texto "Imagen (Tamaño ideal Ancho 600px y 162px de Alto)" por este texto "Imagen (Tamaño ideal Ancho 547px y 309px de Alto)"
5.Al subir la imagen del tamaño 547x309 debería funcionar perfectamente (ya que es la imagen del tempalte) pero no se puede hacer el upload, probar con el adjunto que es la imagen del template:

![bigimg](https://user-images.githubusercontent.com/35821871/39646998-a5677d74-4fb3-11e8-8700-124a82940ce1.png)

**Comment by angeledugo** [comment]
Issues actualizados
por favor validar

**Comment by robert-dm** [comment]
ok
