### ISSUE TITLE
Eventos - Botones y background

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#18]
El background de los botones debe coincidir con el que se ingresó en el formulario, esto no está funcionando.

http://ifd.sietepuentes.com/generar.php?id=70&tipo=news&oper=HTML&template=2

![image](https://user-images.githubusercontent.com/35821871/39647863-e420fa4c-4fb6-11e8-9247-dae776db09dd.png)

**Comment by robert-dm** [comment]
ok

**Comment by angeledugo** [comment]
Listo se realizaron ajustes para botones
