### ISSUE TITLE
IFD News - Agregar imagen al crear

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#2]
No pude agregar la imagen al crear. Si lo pude hacer al editar

**Comment by angeledugo** [comment]
Validar se cargo imagen en desarrollo y se visualiza correctamente lo puedes verificar con uno de los ejemplos cargados

**Comment by carlos-segovia** [comment]
No se puede cargar imagen cuando se crea un IFD Nuevo
Le doy click en Browse, selecciono la imagen pero después queda así:
![image](https://user-images.githubusercontent.com/34341691/39193764-a4a190d6-47b2-11e8-9581-ac837f9b52b9.png)
y obviamente no sube la imagen.

**Comment by angeledugo** [comment]
si cuando selecciona la imagen y le indicas upload ya el la envia al servidor y guarda en el modulo el nombre que es lo que permite actualizar la tabla pero ya esta funciona correctamente

**Comment by carlos-segovia** [comment]
El upload aparece solo si se va a recortar la imagen. Si seleccionas una imagen de 560 x 210 por ej, no aparece el upload y no se puede subir.
Por otro lado, si aparece y le das click en upload queda así:
![image](https://user-images.githubusercontent.com/34341691/39198409-60c008e2-47bd-11e8-9822-dd227ee2154b.png)
Dice: "No file selected" y si esta seleccionado. Deberia aparecer el nombre de la imagen seleccionada.

**Comment by angeledugo** [comment]
Acabo de volver a probar subir una imagen con una dimension de 560 * 210 y se sube correctamente 
http://ifd.sietepuentes.com/generar.php?id=125&tipo=ifdnew&oper=HTML&template=2

les dejo la imagen usada con dichas dimensiones 
![prueba](https://user-images.githubusercontent.com/1197496/39200069-b7fb2612-47b0-11e8-8b23-811c3064c862.png)

**Comment by carlos-segovia** [comment]
lo verifique y el issue se da cuando la imagen es menor a 560 x 210
por ejemplo  la siguiente imagen que es 510 x 209 no sube
![image](https://user-images.githubusercontent.com/34341691/39200613-05913486-47c3-11e8-8d0a-519238e4caa2.png)

**Comment by angeledugo** [comment]
Voy a validar con la imagen enviada

**Comment by angeledugo** [comment]
Listo ya se encuentra validado como valor minimo solicita 500 * 110

**Comment by carlos-segovia** [comment]
Si la imagen es menor a 500 * 110 no sube y no avisa nada. Para solucionarlo fácil en vez de 500 * 110 ponle 1 x 1 asi suben imagenes de cualquier tamaño.

**Comment by angeledugo** [comment]
Ok listo ya lo coloco

**Comment by angeledugo** [comment]
Listo actualizado

**Comment by carlos-segovia** [comment]
Ahora funciona pero se perdió la redirección despues de agregar nuevo o de editar. Queda en el form como antes.

**Comment by carlos-segovia** [comment]
Solucionado.
