### ISSUE TITLE
Agregar link

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#22]
El link se agrega siempre al principio de la caja, se deberia agregar donde este posicionado el cursor.
![image](https://user-images.githubusercontent.com/34341691/40736318-171d0104-6414-11e8-859e-c261bfde6b8e.png)
Si lo pinto y hago click en agregar link si lo hace bien.

**Comment by afc-legio** [comment]
este plugin utilizado está pensado para funcionar así, seleccionar el texto y pulsar el botón
no tiene opción para insertar donde esté el cursor, si no hay nada seleccionado lo inserta al inicio.
si esa funcionalidad es fundamental habría que cambiar el plugin utilizado

**Comment by carlos-segovia** [comment]
Ok, lo dejamos así. Que lo pruebe el usuario y si nos piden el cambio te avisamos.
