### ISSUE TITLE
Eventos - Texto Superior

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#23]
![image](https://user-images.githubusercontent.com/34341691/40737980-ae352d9c-6418-11e8-8e66-81e42deff16b.png)
1. Donde dice "Ingrese Footer Text" cambiarlo por "Ingrese texto superior.
2. Poner este imput text al principio del formulario, porque en la vista se muestra arriba:
![image](https://user-images.githubusercontent.com/34341691/40738860-fecc595e-641a-11e8-9958-03b38cbee8f5.png)

**Comment by afc-legio** [comment]
- hechos cambios indicados
- aparte corregido codigo porque no estaba completamente implementado para este campo

**Comment by robert-dm** [comment]
OK
