### ISSUE TITLE
Eventos - Formato de Texto Izquierda, Texto Centrado y Texto Derecho

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#24]
Asi está en la maqueta:
![image](https://user-images.githubusercontent.com/34341691/40738437-f23e9a2c-6419-11e8-8ac9-8af67184c0a7.png)
Asi se ve ahora:
![image](https://user-images.githubusercontent.com/34341691/40738358-bc90a6d6-6419-11e8-9e7b-d4d444d570a6.png)

1) solo el Texto Izquierda debe ir en bold (negrita)
2) el separador de estos campos es un - (guión) no un . (punto)

**Comment by afc-legio** [comment]
corregido

**Comment by robert-dm** [comment]
Probado, ok.
