### ISSUE TITLE
Eventos - Subtitulo

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#25]
El subtitulo ahora es una caja:
![image](https://user-images.githubusercontent.com/34341691/40738936-3edddeaa-641b-11e8-9003-b8f7996e4ca8.png)

Cambiarlo por un imput text igual al del título:
![image](https://user-images.githubusercontent.com/34341691/40738960-50c9a9aa-641b-11e8-8aad-f5e30f35d70a.png)

**Comment by afc-legio** [comment]
cambiado

**Comment by robert-dm** [comment]
ok, probado.
