### ISSUE TITLE
Eventos - Descripción y Comentario final después de los módulos.

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#26]
Esta es la imagen de la maqueta:
![image](https://user-images.githubusercontent.com/34341691/40739979-f1e57a4c-641d-11e8-97ce-33beb82906f4.png)

Asi es como se esta viendo ahora:
![image](https://user-images.githubusercontent.com/34341691/40740031-1529e7f4-641e-11e8-8b5a-5fbf943ffd4c.png)

1. El espacio entre el borde superior y el texto es mayor en la maqueta. Lo que ví de distinto en el codigo es que la maqueta contiene el texto dentro de una etiqueta de parrafo <p> y el que esta hecho lo hace dentro de un <div> no se si sera este el motivo de la menor separación.

2. En el comentario final hay que corregir el tamaño de la tipografia, en la maqueta es mucho menor.

**Comment by afc-legio** [comment]
- corregido tamaño texto comentario final
- los margenes verticales dependen del contenido, ya que ese elemento tiene altura fija y el contenido se centra verticalemten
