### ISSUE TITLE
Eventos - Formulario de edición - Campos Texto Superior y Footer Text

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#27]
1. Cuando carga el formulario para editar NO carga los valores guardados para Texto Superior y Footer Text.
2. Si agrego texto en estos dos campos no los guarda.

**Comment by afc-legio** [comment]
- campo "Texto Superior" ya se había arreglado en issue #23 
- completado código faltante para campo "Footer Text"
