### ISSUE TITLE
ifd2 templates  - Alertas digitales limite de texto en textarea (quitar)

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/ifd-templates#28]
http://ifd2.sietepuentes.com/generar.php?id=4&tipo=alertdig3&oper=HTML&template=2

El texto se corta en los campos de text area, deben ser textos sin límite.   Por favor revisar todos los templates de Alertas Digitales

![image](https://user-images.githubusercontent.com/38145241/40749998-36ea9f46-643c-11e8-9747-327f8502b70a.png)

**Comment by afc-legio** [comment]
es por el tipo de campo utilizado en la bd, que tiene limites maximos
cambiado en todas las tablas de alertas el tipo de campo para Intro y Contenido (textareas) a TEXT
