### ISSUE TITLE
ifd2 templates - Alertas digitales - Generar html con nombre diferente a test.html

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/ifd-templates#29]
Podemos hacer que al generar el html no se guarden con el nombre text.html, sino que se guarden con el titulo de alerta digital? o alerta_digital1.html, alerta_digital2.html, etc.?

**Comment by afc-legio** [comment]
puesto que el fichero html a descargar tenga como nombre el titulo del elemento
