### ISSUE TITLE
IFD News - Acción después de Aceptar la edición o la creación

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#3]
Al hacer click en el boton Aceptar para confirmar agregar o editar los cambios se guardan pero queda la misma pantalla y no se sabe si se insertó correctamente.
Después de Aceptar debe redireccionar a la página 
variableDominio/news.php

**Comment by angeledugo** [comment]
De la misma manera agregue una nueva news y me redirecciona al listado principal validar nuevamente

**Comment by carlos-segovia** [comment]
Ahora si redirecciona.
