### ISSUE TITLE
ifd2 - alertas digitales - la imagen cargada se ve deformada

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/ifd-templates#30]
Ver este ejemplo
http://ifd2.sietepuentes.com/generar.php?id=3&tipo=alertdig3&oper=HTML&template=2

Se subió la imagen que está acá 
http://ifd2.sietepuentes.com/newsletter/1527719219.jpg

Pero al redimensionarse queda como deformada en lo alto, como si se mostrara en otras dimensiones.
![image](https://user-images.githubusercontent.com/38145241/40750987-abe96388-643f-11e8-862d-d9f415a12bf4.png)

Revisar por favor los tres templates

**Comment by afc-legio** [comment]
generacion templates alertas digitales: quitada altura fija imagen y su contenedor
