### ISSUE TITLE
ifd2 - alerta digital 3 - el texto tiene otra fuente en este ejemplo

### ISSUE THREAD

**Issue by sietepuentes** [sietepuentes/ifd-templates#31]
http://ifd2.sietepuentes.com/generar.php?id=4&tipo=alertdig3&oper=HTML&template=2 

![image](https://user-images.githubusercontent.com/38145241/40751082-108b829e-6440-11e8-8efa-2532cc25a662.png)

La fuente no es la misma que estaba en el template, de hecho es diferente a la fuente de este template donde sí es correcta:
http://ifd2.sietepuentes.com/generar.php?id=3&tipo=alertdig3&oper=HTML&template=2

![image](https://user-images.githubusercontent.com/38145241/40751093-1e91fe18-6440-11e8-8551-4feadc775321.png)

**Comment by robert-dm** [comment]
Esto sucede aparentemente cuando se copia texto de un word con pre formato por ejemplo 
No se respeta el formato del template...

**Comment by afc-legio** [comment]
activado mostrado boton "Remove Styles" en editor html de las alertas digitales
si se pega desde word, utilizar este boton para borrar los estilos que puedan venir desde word

**Comment by robert-dm** [comment]
En el ejemplo se sigue mostrando mal la fuente.
http://ifd2.sietepuentes.com/generar.php?id=4&tipo=alertdig3&oper=HTML&template=2

Voy a edit:
http://ifd2.sietepuentes.com/altaAlertDig3.php?id=4&oper=edit

Presiono el botón "Remove Styles"
Guardo
Pero sigue mostrándose mal.

Podemos forzar que siempre se guarden sin styles y se mantenga la fuente de la maquetación?

**Comment by afc-legio** [comment]
- he probado el boton de "borrar estilo" en dicha alerta digital (campo intro) y sí borró los estilos pegados del word
- en la template de alerta digital 3 había un estilo para los parrafos que hacía se cambiara la tipografía de estos dentro del contenedor para los campos intro y descripcion => quitado dicho estilo parrafo
- he puesto en las clases para los tres tipos de alerta digital, que para valor campos intro y descripcion se quiten param styles de tags html

**Comment by carlos-segovia** [comment]
Listo! funciona OK.
