### ISSUE TITLE
IFD - Publicaciones Mensuales - Aceptar no funciona

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#32]
Al crear un registro:
http://ifd.sietepuentes.com/altaNewsmonth.php?oper=add

Clickear en el botón Aceptar, debe guardar y redireccionar al listado, pero no está funcionando.
![image](https://user-images.githubusercontent.com/35821871/40797871-ef003110-64df-11e8-81ba-24d069fff560.png)

**Comment by afc-legio** [comment]
corregido

**Comment by robert-dm** [comment]
Al apretar el botón ACEPTAR, se guarda el template, pero falta el redirect al listado de templates publicaciones del mes.  Porque apreto aceptar pero queda ahí y no está claro si se guardó o no.

**Comment by afc-legio** [comment]
- estaba dando error al guardar porque faltaba tabla en bd para los modulos (bid_newsmonth_modulo_info) => creada
- vuelto a probar a guardar registro, ahora ya no da error, guarda todo ok en bd y redirige a listado

**Comment by afc-legio** [comment]
no reproduzco problema al dar a aceptar en nueva publicacion mes.
he creado una sin problemas ("Nueva prueba").

**Comment by robert-dm** [comment]
Funciona ok
