### ISSUE TITLE
IFD - Publicaciones mensuales - No se puede visualizar el template

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#33]
Al crear el template lo veo en el listado, pero si ingreso al botón "ver" me redirecciona y me aparece este error:

http://ifd.sietepuentes.com/generar.php?id=8&tipo=newsMonth&oper=HTML
Fatal error: Uncaught exception 'ErrorException' with message 'Problem preparing query (select pub.* from bid_newsmonth_modulo_info pub where pub.IDNewsMonth= '8') Table 'ifdtempl_bid.bid_newsmonth_modulo_info' doesn't exist' in /var/www/html/ifd-templates/prog/frm/core/MysqliDb.php:904 Stack trace: #0 [internal function]: Config::exceptionErrorHandler(256, 'Problem prepari...', '/var/www/html/i...', 904, Array) #1 /var/www/html/ifd-templates/prog/frm/core/MysqliDb.php(904): trigger_error('Problem prepari...', 256) #2 /var/www/html/ifd-templates/prog/frm/core/MysqliDb.php(218): MysqliDb->_prepareQuery() #3 /var/www/html/ifd-templates/prog/app/mcc/clases/BidNewsMonthModuloInfo.class.php(196): MysqliDb->rawQuery('select pub.* fr...') #4 /var/www/html/ifd-templates/generar.php(374): BidNewsMonthModuloInfo::listadoModulos('8') #5 {main} thrown in /var/www/html/ifd-templates/prog/frm/core/MysqliDb.php on line 904

![image](https://user-images.githubusercontent.com/35821871/40854313-68727540-65a7-11e8-9c7b-267ab16bea60.png)

**Comment by afc-legio** [comment]
es el mismo error solucionado en la #32

**Comment by robert-dm** [comment]
Funciona bien.
