### ISSUE TITLE
IFD - Publicaciones del mes - Editar muestra el form vacío

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#34]
Voy a editar un template creado y se muestra el form vacío sin los datos cargados.

http://ifd.sietepuentes.com/altaNewsmonth.php?id=8&oper=edit
![image](https://user-images.githubusercontent.com/35821871/40854352-85cada88-65a7-11e8-9786-7cc3765d2c18.png)

**Comment by afc-legio** [comment]
corregido

**Comment by robert-dm** [comment]
OK
