### ISSUE TITLE
IFD - Eventos - Se multiplican los campos de pantalla al Agregar Modulo

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#35]
En ifd.sietepuentes.com
Eventos - Agregar
Completo el template
Agrego un modulo
Agrego otro módulo

Los campos descripción, descripción final, se empiezan a duplicar.  si vuelvo a agregar otro módulo, se muestra otro campo más, y no se entiende donde se debe ingresar el texto.

Los campos que se duplican y multiplican son los que tienen el plugin de edición de texto
-Descripcion final (solo debe existir un campo textarea con este título) 
-Comentario Final (solo debe existir un campo textarea con este título) 

También al agregar un nuevo módulo, se duplica el campo descripción con el plugin del primer módulo agregado.

**Comment by afc-legio** [comment]
eventos: al agregar modulo puesto que solo se active plugin editor html sobre los textarea de ese nuevo modulo

**Comment by carlos-segovia** [comment]
Listo! solucionado.
