### ISSUE TITLE
IFD - Publicaciones del Mes - La imagen no se muestra

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#36]
1) Creo un template de Publicaciones Mensuales.  subo una imagen
2) Al visualizar el template, no se visualiza la imagen

En el php de edición se ve la imagen:
http://ifd.sietepuentes.com/altaNewsmonth.php?id=12&oper=edit
![image](https://user-images.githubusercontent.com/35821871/40933487-f9aeeeaa-6807-11e8-82dc-367328eb731b.png)

En el view no:
http://ifd.sietepuentes.com/generar.php?id=12&tipo=newsMonth&oper=HTML
![image](https://user-images.githubusercontent.com/35821871/40933521-09fcfafe-6808-11e8-9eff-d335fb3816d3.png)

En el export a html, tampoco se visualiza la imagen.

**Comment by afc-legio** [comment]
estaba mal el dominio usado para la url de la imagen, corregido

**Comment by robert-dm** [comment]
funciona ok
