### ISSUE TITLE
IFD - Publicaciones mensuales - Edicion

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#37]
Al editar un form de Publicaciones del mes, existen los siguientes issues:

1) El botón ACEPTAR no hace nada
2) Aparece \n en varias partes de la pantalla:

![image](https://user-images.githubusercontent.com/35821871/40934020-cc9b5686-6809-11e8-9202-46955d0d6bd2.png)

**Comment by afc-legio** [comment]
- corregido error que saltaba al dar a aceptar (mal nombre de tabla bd usada)
- quitados los \n\

**Comment by robert-dm** [comment]
ok corregido
