### ISSUE TITLE
IFD - Publicaciones del mes - Imagen del template

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#38]
Al subir la imagen que está en la maquetación (la del calendario) http://ifd.sietepuentes.com/_maquetas/4-Publicaciones%20Mensuales/images/bigImg.png  no se puede redimensionar correctamente.

Pareciera que el image resize al hacer upload tiene otras dimensiones y otro tamaño:

![image](https://user-images.githubusercontent.com/35821871/40934147-398aae2c-680a-11e8-8e3d-13025e6b93f9.png)

**Comment by afc-legio** [comment]
ajustado tamaño redimension imagen al de la maqueta (560x221)

**Comment by robert-dm** [comment]
Este error me sigue sucediendo, estoy intentando subir la imagen de la maqueta y el área de ajuste es mayor a la imagen.  Adjunto la imagen que quiero hacer upload y me sucede esto

![image](https://user-images.githubusercontent.com/35821871/41011740-a13fb55c-6914-11e8-92b5-a0307f08cf54.png)

imagen bgImg.png
![bigimg](https://user-images.githubusercontent.com/35821871/41011746-a6c18528-6914-11e8-8b5d-323b560b9e46.png)

**Comment by afc-legio** [comment]
cambiadas dimensiones minimas resizer a 536x204

**Comment by robert-dm** [comment]
testeado. funciona ok.
