### ISSUE TITLE
IFD - Eventos - Módulo

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#39]
El texto se superpone al botón

http://ifd.sietepuentes.com/generar.php?id=84&tipo=news&oper=HTML&template=2

![image](https://user-images.githubusercontent.com/34341691/40934128-2ba0abcc-680a-11e8-9360-f8c76a909051.png)

**Comment by afc-legio** [comment]
quitada height fija para ese contenido

**Comment by robert-dm** [comment]
Verificado, ok.
