### ISSUE TITLE
IFD News - Footer box

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#4]
El rectangulo azul donde va el texto del footer y las redes sociales le falta un pedazo si no esta el texto y hay redes. Es decir, no queda un rectángulo azul.
![image](https://user-images.githubusercontent.com/34341691/39147016-d95aaa64-470e-11e8-946a-0ac61f474b5e.png)

**Comment by angeledugo** [comment]
Hola carlos acabo de hacer una prueba colocando el footer y la hace de manera correcta

**Comment by carlos-segovia** [comment]
El issue es cuando NO hay texto de footer como en la siguiente imagen:
![image](https://user-images.githubusercontent.com/34341691/39193549-3347d88c-47b2-11e8-852b-ac091a80f0e6.png)

**Comment by angeledugo** [comment]
se actualizo la dimension para el caso de tener footer text

**Comment by carlos-segovia** [comment]
Ahora no esta funcionando la edición. Cuando quiero guardar los cambios que hice al editar no hace nada.

**Comment by angeledugo** [comment]
ni justo en el momento que realizastes la prueba estaba validando en desarrollo por eso no te guardo 
por favor valida que te edite y te permita cargar nuevos modulos acabo de probar con el ultimo y lo hizo correctamente solo queda validar para dimensiones inferiores

**Comment by carlos-segovia** [comment]
Ahora si anda.
![image](https://user-images.githubusercontent.com/34341691/39203851-6bd369f4-47cc-11e8-9643-b079aaa1a23d.png)
