### ISSUE TITLE
IFD - Publicaciones del mes - Falta plugin formato de texto

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#40]
1) Agregar nuevo template
2) Ir a Agregar Módulo
3) El campo descripción debe tener el plugin para permitir incluir hyperlinks (y quitar formato)

![image](https://user-images.githubusercontent.com/35821871/40934179-5d002b8e-680a-11e8-82c2-d3de98b91f09.png)

**Comment by afc-legio** [comment]
agregar modulo: aplicado plugin editor html a textareas nuevo modulo

**Comment by robert-dm** [comment]
Por favor incluir la opción de resetear el formato de estilos por si pegan texto desde Word.  Esto en todos los templates que haya plugin por favor

![image](https://user-images.githubusercontent.com/35821871/41011865-44f0f4e0-6915-11e8-8455-580de11b822a.png)

**Comment by afc-legio** [comment]
mostrado boton borrar estilos en todas las instancias usadas del plugin editor html

**Comment by robert-dm** [comment]
Ok, el botón está, pero no quita todos los estilos.

Por favor revisar este ejemplo, el estilo del texto queda diferente a la maquetación:
http://ifd.sietepuentes.com/generar.php?id=14&tipo=newsMonth&oper=HTML

![image](https://user-images.githubusercontent.com/35821871/41033218-18da970c-695c-11e8-9cb1-f397f980d19e.png)

Así es como se debe ver el resultado final:
http://ifd.sietepuentes.com/_maquetas/4-Publicaciones%20Mensuales/index.html
![image](https://user-images.githubusercontent.com/35821871/41033238-2d28fdb6-695c-11e8-875f-10ccaab45860.png)

**Comment by afc-legio** [comment]
aplicado color correcto template a contenedor campo descripcion modulo

**Comment by robert-dm** [comment]
Perfecto.
