### ISSUE TITLE
IFD - Eventos - Comentario final con link

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#41]
cuando se agregué un link en comentario final debe mantener el mismo color, solo agregar subrayado en el link.
Ahora se ve asi:
![image](https://user-images.githubusercontent.com/34341691/40934219-884f71d2-680a-11e8-89db-b59d289d3851.png)

**Comment by afc-legio** [comment]
sobrescrito color enlaces para comentario final

**Comment by robert-dm** [comment]
Verificado, ok.
![image](https://user-images.githubusercontent.com/35821871/41011854-2c799e12-6915-11e8-9f39-4fe8a761bd9a.png)
