### ISSUE TITLE
IFD - Publicaciones del mes - Falta "texto del boton"

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#42]
En el form de Publicaciones del mes (Agregar y Editar)
En cada módulo
El botón debe tener un link, y además, un texto, por favor agregar el texto para el botón (luego se debe mostrar en el view y en el generate este texto, en vez de "Read More" siempre fijo"

![image](https://user-images.githubusercontent.com/35821871/40934249-9a983090-680a-11e8-8700-81c43742c90c.png)

![image](https://user-images.githubusercontent.com/35821871/40934305-c6fef3e4-680a-11e8-8d2a-1f375944f05a.png)

**Comment by afc-legio** [comment]
añadido campo TextoBoton a modulo publicacion mes (tabla bd y codigo)

**Comment by robert-dm** [comment]
Perfecto, ok
