### ISSUE TITLE
IFD - Publicaciones del mes - Listar en modo descendente en base a fecha de creación

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#43]
Por favor listar los registros en modo descendente:

![image](https://user-images.githubusercontent.com/35821871/40934388-0350dd08-680b-11e8-8ae5-f515a562c827.png)

**Comment by afc-legio** [comment]
cambiado orden listado

**Comment by robert-dm** [comment]
Verificado, ok.
