### ISSUE TITLE
IFD - Eventos - Redes Sociales

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#44]
http://ifd.sietepuentes.com/generar.php?id=84&tipo=news&oper=HTML&template=2

1. NO esta tomando los links de ninguna de las redes.
Por ejemplo si hago click en la imagen de facebook el link que aparece es: 
http://ifd.sietepuentes.com/generar.php?id=84&tipo=news&oper=HTML&template=2#
pero el que esta guardado en la base y al cual debería apuntar es: https://www.facebook.com/NikeAirMaxOffeciel/

2. La separación entre las imagenes de redes no es la misma, en este ejemplo google e instagram estan mas pegados que los demas:
![image](https://user-images.githubusercontent.com/34341691/40934467-3cdab7b0-680b-11e8-8148-8cd0972fef51.png)

**Comment by afc-legio** [comment]
- corregido no se estaba usando en enlaces redes sociales el valor campo metido
- añadida separacion faltante antes icono google+

**Comment by robert-dm** [comment]
Validado, funcionan correctamente los links y la separación se ve ok.

![image](https://user-images.githubusercontent.com/35821871/41033338-8bc556da-695c-11e8-8c31-99e3dd3b4ad3.png)
