### ISSUE TITLE
IFD2 - Alerta digital 1, 2, 3 ,subject in browser

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#45]
En todas las pestañas de browser(en todos los casos de Alertas digitales 1 2 y 3) se visualiza SUBJECT al abrir el template, podemos cambiarlo por el nombre del registro? o el título del template? pero que no se vea SUBJECT.

![image](https://user-images.githubusercontent.com/35821871/41117203-bbe4498c-6a62-11e8-914b-25934fc35236.png)

**Comment by afc-legio** [comment]
mostrado titulo elemento en <title> templates alertas digitales

**Comment by robert-dm** [comment]
ok
