### ISSUE TITLE
IFD2 - Email body no contiene las imágenes

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#46]
Para los tres Alerta Digital... es un issue común.
El proceso que siguen los usuarios es generar el html, y luego Insertar como texto en Outlook el html descargado a su PC, y se muestra en el body del email de Outlook a enviar.  
Esto funciona bien, pero cuando llega el mail a los destinatarios, no se muestran las imágenes (cuando hacen click en open in browser, las imágenes sí se ven), por ejemplo así llegan los emails:

![image](https://user-images.githubusercontent.com/35821871/41117318-14a4a5e4-6a63-11e8-982a-90a00ca6df81.png)

Adjunto el email donde no se ven las imágenes (estas deben tener path relativos en el html generado, y no se imágenes incluidas en el html, no se si me explico).

Este es el mail tal cual llega a los usuarios....
[Prueba.zip](https://github.com/sietepuentes/ifd-templates/files/2081875/Prueba.zip)

**Comment by afc-legio** [comment]
- en el html de la template se usan urls absolutas para las imágenes
- lo que veo en el email que me mandas es efectivamente que las imágenes tienen url relativas, pero locales respecto a su ordenador, no respecto al sitio
- cuando descarguen el html de la template, que descarguen solo el html de la pagina, no la pagina completa, porque entonces se le descargan también a local todos las imágenes y se cambian las urls de estas a las locales descargadas; luego que prueben a enviar ese html descargado

**Comment by robert-dm** [comment]
ok
