### ISSUE TITLE
IFD / IFD2 - URL hard-codeada en generar.php file

### ISSUE THREAD

**Issue by robert-dm** [sietepuentes/ifd-templates#47]
Agustín,

Porfa podrías reemplazar en ifd2 y en ifd en todos lados donde figure "ifd.sietepuentes.com" y "ifd2.sietepuentes.com" hard-coded por alguna variable, así podemos implementar los cambios en otro servidor y pueda funcionar? nos pasó que implementamos en otra URL las alertas digitales, pero están apuntando al generar el php a ifd2.sietepuentes.com

Gracias!

**Comment by afc-legio** [comment]
- en el Config.php del sistema (prog/frm/core/) ya hay definida una constante para la url del sitio => WEB_ROOT_URL
- modificado el generar.php de ifd / ifd2 para sustituir el dominio hardcoded por el uso de dicha constante

**Comment by robert-dm** [comment]
perfecto.
