### ISSUE TITLE
IFD News - Texto tamaño de imagenes

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#6]
El texto del campo para subir las imagenes dice: (Tamaña ideal Ancho 238px y 312px de Alto)
![image](https://user-images.githubusercontent.com/34341691/39147706-c2a0c43c-4710-11e8-9bde-0c49de895c45.png)

![image](https://user-images.githubusercontent.com/34341691/39147691-b60f1afc-4710-11e8-9259-7c9c3a0f4fac.png)

Deberia decir: 
(Tamaña ideal Ancho 560px y 210px de Alto)

**Comment by angeledugo** [comment]
Actualize el javascript que indica las dimensiones ya debe aparecer correcto

**Comment by carlos-segovia** [comment]
en agregar si esta bien
![image](https://user-images.githubusercontent.com/34341691/39193400-d8be82e4-47b1-11e8-96b2-451756421008.png)

en edición sigue apareciendo el anterior:
![image](https://user-images.githubusercontent.com/34341691/39193363-c3f9f898-47b1-11e8-9593-85028249be86.png)

**Comment by angeledugo** [comment]
Este issue fue completado

**Comment by robert-dm** [comment]
Aparece el tamaño correcto
