### ISSUE TITLE
IFD News - Tamaño de imagen recortada

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#7]
Cuando subimos una imagen mayor al tamaño sugerido da la opción de recortar y el rectángulo de recorte aparece de 1,024px × 384px y deberia ser de 560px x 210px

**Comment by angeledugo** [comment]
Este punto no se donde aparecen estas medidas no lo he tocado deberia estar igual

**Comment by carlos-segovia** [comment]
Las medidas son las de la imagen del html modelo.

**Comment by angeledugo** [comment]
esto ya esta actualizado

**Comment by carlos-segovia** [comment]
Sube la imagen del tamaño original ahora no aparece el redimensionar en la edición.
En nuevo aparece el redimensionar pero corta la imagen en 691px × 259px

**Comment by angeledugo** [comment]
este script de subir la imagen en la edicion no contiene la redimension como cuando agregas una nueva que usa el plugin jcrop

**Comment by carlos-segovia** [comment]
Ok, Lo dejamos así.
