### ISSUE TITLE
IFD News - Texto del Boton del segundo módulo

### ISSUE THREAD

**Issue by carlos-segovia** [sietepuentes/ifd-templates#9]
El boton: 
![image](https://user-images.githubusercontent.com/34341691/39193940-021dbe4c-47b3-11e8-97dd-a7be454a4a0e.png)
apunta correctamente al link del segundo módulo pero tiene un texto fijo, es decir, no toma el texto del boton del segundo módulo.

**Comment by angeledugo** [comment]
se actualiza el boton dinamicamente

**Comment by angeledugo** [comment]
Solucionado el item por favor validar

**Comment by carlos-segovia** [comment]
Listo!
![image](https://user-images.githubusercontent.com/34341691/39211658-b546ff40-47e2-11e8-9c1c-aedc675535b3.png)
